[package]
name = "openssl"
version = "0.2.0"
description = "OpenSSL is a robust, commercial-grade, and full-featured toolkit for the Transport Layer Security (TLS) and Secure Sockets Layer (SSL) protocols"
readme = "README.md"
repository = "https://github.com/wapm-packages/OpenSSL"

[[module]]
name = "openssl"
source = "openssl.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.0.0-unstable"

# [[module]]
# name = "libcrypto"
# source = "libcrypto.wasm"

# [[module]]
# name = "libssl"
# source = "libssl.wasm"

[[command]]
name = "openssl"
module = "openssl"
