[package]
name = "openssl"
version = "0.1.0"
description = "OpenSSL is a robust, commercial-grade, and full-featured toolkit for the Transport Layer Security (TLS) and Secure Sockets Layer (SSL) protocols"
readme = "README.md"
repository = "https://github.com/wapm-packages/OpenSSL"

[[module]]
name = "openssl"
source = "openssl.wasm"
abi = "emscripten"

[[command]]
name = "openssl"
module = "openssl"
